%% ============================================================
% Question 3(d)
% Stationary Linear Quadratic Servo Controller
%% ============================================================

clear
close all
clc

%% ============================================================
% 1. Aircraft model
%
% State vector:
% x = [beta  p  r  phi  delta_a]'
%% ============================================================

A = [ ...
    -0.575     0       -1       0.0536   -0.078;
    -300      -3.03     2       0        64.4;
      68       0.045   -2.4     0         5;
       0       1        0       0         0;
       0       0        0       0        -5];

B = [0; 0; 0; 0; 5];

C_phi = [0 0 0 1 0];

n = size(A,1);

%% ============================================================
% 2. Augmented servo model
%
% xi_dot = phi_c - phi
% xa = [x; xi]
%% ============================================================

A_aug = [ ...
    A,              zeros(n,1);
   -C_phi,          0];

B_aug = [B; 0];

% Reference input enters the integral-state equation
E_ref = [zeros(n,1); 1];

%% Augmented controllability check

Co_aug = ctrb(A_aug,B_aug);
rank_Co_aug = rank(Co_aug);

fprintf('Augmented controllability rank = %d\n', ...
    rank_Co_aug)

if rank_Co_aug ~= n+1
    error('The augmented system is not completely controllable.')
end

%% ============================================================
% 3. LQ Servo design
%% ============================================================

Q = diag([ ...
    0.1, ...      % beta
    0.001, ...    % p
    0.001, ...    % r
    10, ...       % phi
    0.001, ...    % delta_a
    100]);        % integral tracking error

R = 100;

% K_aug  - LQ feedback gain
% P_riccati - solution of the algebraic Riccati equation
% poles_lqr - closed-loop poles
[K_aug,P_riccati,poles_lqr] = ...
    lqr(A_aug,B_aug,Q,R);

poles_lqr = poles_lqr(:);

A_cl = A_aug-B_aug*K_aug;

K_x = K_aug(1:5);
K_i = K_aug(6);

%% ============================================================
% 4. Verification of the Riccati equation
%
% A'P + PA - PBR^(-1)B'P + Q = 0
%% ============================================================

riccati_residual = ...
    A_aug'*P_riccati ...
    + P_riccati*A_aug ...
    - P_riccati*B_aug*(R\B_aug')*P_riccati ...
    + Q;

riccati_error = norm(riccati_residual,'fro');

K_check = R\(B_aug'*P_riccati);
gain_error = norm(K_aug-K_check);

fprintf('\n============================================\n')
fprintf('LQ SERVO DESIGN\n')
fprintf('============================================\n')

fprintf('\nLQ gain K_aug:\n')
disp(K_aug)

fprintf('State-feedback part K_x:\n')
disp(K_x)

fprintf('Integral gain K_i:\n')
fprintf('K_i = %.8f\n',K_i)

fprintf('\nRiccati residual norm = %.4e\n', ...
    riccati_error)

fprintf('Gain verification error = %.4e\n', ...
    gain_error)

fprintf('\nClosed-loop poles:\n')
disp(poles_lqr)

%% ============================================================
% 5. Closed-loop systems
%% ============================================================

% Output all six augmented states
sys_aug_states = ss( ...
    A_cl, ...
    E_ref, ...
    eye(n+1), ...
    zeros(n+1,1));

% Output roll angle phi only
C_phi_aug = [C_phi 0];

sys_phi = ss( ...
    A_cl, ...
    E_ref, ...
    C_phi_aug, ...
    0);

sys_phi.Name = 'LQ Servo';

%% ============================================================
% 6. Nominal 30-degree command simulation
%% ============================================================

phi_command_deg = 30;
phi_command_rad = deg2rad(phi_command_deg);

t = (0:0.001:10)';
r = phi_command_rad*ones(size(t));

x_aug_0 = zeros(n+1,1);

x_aug_response = lsim( ...
    sys_aug_states, ...
    r, ...
    t, ...
    x_aug_0);

%% Separate the states

x = x_aug_response(:,1:5);
x_i = x_aug_response(:,6);

phi_deg = rad2deg(x(:,4));
delta_a_deg = rad2deg(x(:,5));

%% Control command

% delta_c = -K_aug*x_aug
delta_c_rad = -x_aug_response*K_aug.';
delta_c_deg = rad2deg(delta_c_rad);

%% Tracking error

tracking_error_deg = ...
    phi_command_deg-phi_deg;

%% ============================================================
% 7. Performance calculations
%% ============================================================

phi_final_deg = ...
    phi_command_deg*real(dcgain(sys_phi));

steady_state_error_deg = ...
    phi_command_deg-phi_final_deg;

info = stepinfo( ...
    phi_deg, ...
    t, ...
    phi_command_deg, ...
    'SettlingTimeThreshold',0.02);

[max_delta_a,index_delta_a] = ...
    max(abs(delta_a_deg));

[max_delta_c,index_delta_c] = ...
    max(abs(delta_c_deg));

aileron_limit_deg = 5;

meets_aileron_limit = ...
    max_delta_a <= aileron_limit_deg;

fprintf('\n============================================\n')
fprintf('NOMINAL LQ SERVO PERFORMANCE\n')
fprintf('============================================\n')

fprintf('Final phi = %.8f deg\n', ...
    phi_final_deg)

fprintf('Steady-state error = %.8e deg\n', ...
    steady_state_error_deg)

fprintf('Rise time = %.4f s\n', ...
    info.RiseTime)

fprintf('Settling time = %.4f s\n', ...
    info.SettlingTime)

fprintf('Overshoot = %.4f %%\n', ...
    info.Overshoot)

fprintf('Max |delta_a| = %.4f deg\n', ...
    max_delta_a)

fprintf('Max |delta_c| = %.4f deg\n', ...
    max_delta_c)

fprintf('Aileron limit satisfied = %d\n', ...
    meets_aileron_limit)

Results = table( ...
    phi_final_deg, ...
    steady_state_error_deg, ...
    info.RiseTime, ...
    info.SettlingTime, ...
    info.Overshoot, ...
    max_delta_a, ...
    max_delta_c, ...
    meets_aileron_limit, ...
    'VariableNames',{ ...
    'FinalPhiDeg', ...
    'SteadyStateErrorDeg', ...
    'RiseTimeSec', ...
    'SettlingTimeSec', ...
    'OvershootPercent', ...
    'MaxDeltaADeg', ...
    'MaxDeltaCDeg', ...
    'MeetsAileronLimit'});

disp(' ')
disp('LQ Servo results:')
disp(Results)

%% ============================================================
% 8. Pole and zero information
%% ============================================================

closed_loop_poles = pole(sys_phi);
closed_loop_zeros = zero(sys_phi);

fprintf('\nClosed-loop damping information:\n')
damp(sys_phi)

fprintf('\nClosed-loop poles:\n')
disp(closed_loop_poles)

fprintf('Closed-loop zeros:\n')
disp(closed_loop_zeros)

%% ============================================================
% Figure 1
% Pole-zero map with damping-ratio and natural-frequency grid
%
% This is a pole-zero map, not a root locus.
%% ============================================================

figure(1)

set(gcf, ...
    'Color','w', ...
    'Name','LQ Servo Pole-Zero Map', ...
    'Position',[100 100 1050 680])

% pzplot supplies control-system Data Tips:
% pole/zero location, damping ratio and natural frequency
pzplot(sys_phi)

% sgrid accepts only damping ratios:
% 0 < zeta < 1
sgrid( ...
    [0.1 0.2 0.4 0.6 0.8], ...
    [2 4 6 8 10])

title('LQ Servo Closed-Loop Poles and Zeros')

% Do not use:
% set(gca,...)
% datacursormode on
%
% Use the Data Tips button in the figure toolbar.

%% ============================================================
% Figure 2
% Roll-angle response with settling requirements
%% ============================================================

settling_lower = 0.98*phi_command_deg;
settling_upper = 1.02*phi_command_deg;

figure(2)

set(gcf, ...
    'Color','w', ...
    'Name','LQ Servo Tracking Response', ...
    'Position',[130 100 1000 600])

hold on

% Two-percent settling band
fill( ...
    [t(1) t(end) t(end) t(1)], ...
    [settling_lower settling_lower ...
     settling_upper settling_upper], ...
    [0.85 0.93 1.00], ...
    'EdgeColor','none', ...
    'FaceAlpha',0.65, ...
    'DisplayName','\pm2\% settling band');

plot( ...
    t, ...
    phi_deg, ...
    'LineWidth',2.3, ...
    'DisplayName','\phi(t)');

yline( ...
    phi_command_deg, ...
    'k--', ...
    '\phi_c = 30^\circ', ...
    'LineWidth',1.5, ...
    'DisplayName','Command');

xline( ...
    info.RiseTime, ...
    ':', ...
    sprintf('t_r = %.3f s',info.RiseTime), ...
    'LineWidth',1.4, ...
    'HandleVisibility','off');

xline( ...
    info.SettlingTime, ...
    '--', ...
    sprintf('t_s = %.3f s',info.SettlingTime), ...
    'LineWidth',1.4, ...
    'HandleVisibility','off');

grid on
box on

xlabel('Time [s]')
ylabel('\phi [deg]')

title('LQ Servo Tracking of a 30^\circ Roll Command')

legend( ...
    'Location','southeast', ...
    'Interpreter','tex')

xlim([0 4])
ylim([0 32])

%% Correct performance-data box

performance_text = { ...
    sprintf('t_r = %.3f s',info.RiseTime)
    sprintf('t_s = %.3f s',info.SettlingTime)
    sprintf('M_p = %.3f%%',info.Overshoot)
    'e_{ss} \approx 0'};

text( ...
    2.5, ...
    13, ...
    performance_text, ...
    'Interpreter','tex', ...
    'BackgroundColor','w', ...
    'EdgeColor',[0.4 0.4 0.4], ...
    'Margin',7, ...
    'FontSize',10, ...
    'VerticalAlignment','middle');

%% ============================================================
% Figure 3
% Actual aileron deflection and servo command
%% ============================================================

figure(3)

set(gcf, ...
    'Color','w', ...
    'Name','LQ Servo Control Effort', ...
    'Position',[160 60 1000 780])

tiledlayout(2,1)

%% Actual aileron deflection

nexttile

hold on

% Allowed aileron range
fill( ...
    [t(1) t(end) t(end) t(1)], ...
    [-aileron_limit_deg -aileron_limit_deg ...
      aileron_limit_deg  aileron_limit_deg], ...
    [0.88 0.97 0.88], ...
    'EdgeColor','none', ...
    'FaceAlpha',0.7, ...
    'DisplayName','Allowed aileron range');

plot( ...
    t, ...
    delta_a_deg, ...
    'LineWidth',2.2, ...
    'DisplayName','\delta_a(t)');

yline( ...
    aileron_limit_deg, ...
    'r--', ...
    '+5^\circ limit', ...
    'LineWidth',1.6, ...
    'DisplayName','Aileron limit');

yline( ...
    -aileron_limit_deg, ...
    'r--', ...
    '-5^\circ limit', ...
    'LineWidth',1.6, ...
    'HandleVisibility','off');

plot( ...
    t(index_delta_a), ...
    delta_a_deg(index_delta_a), ...
    'ko', ...
    'MarkerFaceColor',[1 0.8 0], ...
    'MarkerSize',7, ...
    'HandleVisibility','off');

text( ...
    t(index_delta_a)+0.1, ...
    delta_a_deg(index_delta_a), ...
    sprintf('max |\\delta_a| = %.2f^\\circ',max_delta_a), ...
    'Interpreter','tex', ...
    'BackgroundColor','w', ...
    'EdgeColor',[0.5 0.5 0.5], ...
    'Margin',4);

grid on
box on

xlabel('Time [s]')
ylabel('\delta_a [deg]')

title('Actual Aileron Deflection and the \pm5^\circ Requirement')

legend( ...
    'Location','southeast', ...
    'Interpreter','tex')

xlim([0 4])
ylim([-6 6])

%% Servo control command

nexttile

plot( ...
    t, ...
    delta_c_deg, ...
    'LineWidth',2.2, ...
    'DisplayName','\delta_c(t)');

hold on

yline( ...
    0, ...
    'k:', ...
    'HandleVisibility','off');

plot( ...
    t(index_delta_c), ...
    delta_c_deg(index_delta_c), ...
    'ko', ...
    'MarkerFaceColor',[1 0.8 0], ...
    'MarkerSize',7, ...
    'HandleVisibility','off');

text( ...
    t(index_delta_c)+0.1, ...
    delta_c_deg(index_delta_c), ...
    sprintf('max |\\delta_c| = %.2f^\\circ',max_delta_c), ...
    'Interpreter','tex', ...
    'BackgroundColor','w', ...
    'EdgeColor',[0.5 0.5 0.5], ...
    'Margin',4);

grid on
box on

xlabel('Time [s]')
ylabel('\delta_c [deg]')

title('Servo Control Command')

legend( ...
    'Location','best', ...
    'Interpreter','tex')

xlim([0 4])

%% ============================================================
% Figure 4
% Tracking error and integral state
%% ============================================================

figure(4)

set(gcf, ...
    'Color','w', ...
    'Name','Tracking Error and Integral State', ...
    'Position',[190 80 1000 750])

tiledlayout(2,1)

%% Tracking error

nexttile

plot( ...
    t, ...
    tracking_error_deg, ...
    'LineWidth',2)

hold on

yline( ...
    0, ...
    'k--', ...
    'Zero tracking error');

grid on
box on

xlabel('Time [s]')
ylabel('e_\phi [deg]')

title('Roll-Angle Tracking Error')

xlim([0 5])

%% Integral state

nexttile

plot( ...
    t, ...
    rad2deg(x_i), ...
    'LineWidth',2)

grid on
box on

xlabel('Time [s]')
ylabel('x_i [deg \cdot s]')

title('Integral State')

xlim([0 5])

%% ============================================================
% 9. Different initial-condition tests
%% ============================================================

x0_case_1 = zeros(6,1);

% beta(0) = 1 deg
x0_case_2 = [ ...
    deg2rad(1);
    0;
    0;
    0;
    0;
    0];

% p(0) = 1 deg/s and phi(0) = -5 deg
x0_case_3 = [ ...
    0;
    deg2rad(1);
    0;
    deg2rad(-5);
    0;
    0];

% delta_a(0) = 1 deg
x0_case_4 = [ ...
    0;
    0;
    0;
    0;
    deg2rad(1);
    0];

initial_conditions = [ ...
    x0_case_1, ...
    x0_case_2, ...
    x0_case_3, ...
    x0_case_4];

case_names = [ ...
    "Zero initial state";
    "beta(0) = 1 deg";
    "p(0) = 1 deg/s, phi(0) = -5 deg";
    "delta_a(0) = 1 deg"];

number_of_cases = size(initial_conditions,2);

phi_cases = zeros(length(t),number_of_cases);
delta_a_cases = zeros(length(t),number_of_cases);
delta_c_cases = zeros(length(t),number_of_cases);

FinalPhi = zeros(number_of_cases,1);
MaxDeltaA = zeros(number_of_cases,1);
MaxDeltaC = zeros(number_of_cases,1);
MeetsAileronLimit = false(number_of_cases,1);

for k = 1:number_of_cases

    x_aug_case = lsim( ...
        sys_aug_states, ...
        r, ...
        t, ...
        initial_conditions(:,k));

    phi_cases(:,k) = ...
        rad2deg(x_aug_case(:,4));

    delta_a_cases(:,k) = ...
        rad2deg(x_aug_case(:,5));

    delta_c_cases(:,k) = ...
        rad2deg(-x_aug_case*K_aug.');

    FinalPhi(k) = ...
        phi_cases(end,k);

    MaxDeltaA(k) = ...
        max(abs(delta_a_cases(:,k)));

    MaxDeltaC(k) = ...
        max(abs(delta_c_cases(:,k)));

    MeetsAileronLimit(k) = ...
        MaxDeltaA(k) <= aileron_limit_deg;
end

InitialConditionResults = table( ...
    case_names, ...
    FinalPhi, ...
    MaxDeltaA, ...
    MaxDeltaC, ...
    MeetsAileronLimit, ...
    'VariableNames',{ ...
    'InitialCondition', ...
    'FinalPhiDeg', ...
    'MaxDeltaADeg', ...
    'MaxDeltaCDeg', ...
    'MeetsAileronLimit'});

disp(' ')
disp('Initial-condition test results:')
disp(InitialConditionResults)

%% ============================================================
% Figure 5
% Initial-condition response comparison
%% ============================================================

figure(5)

set(gcf, ...
    'Color','w', ...
    'Name','Initial Condition Comparison', ...
    'Position',[220 100 1000 600])

hold on

fill( ...
    [t(1) t(end) t(end) t(1)], ...
    [settling_lower settling_lower ...
     settling_upper settling_upper], ...
    [0.85 0.93 1.00], ...
    'EdgeColor','none', ...
    'FaceAlpha',0.55, ...
    'HandleVisibility','off');

for k = 1:number_of_cases

    plot( ...
        t, ...
        phi_cases(:,k), ...
        'LineWidth',1.7, ...
        'DisplayName',case_names(k));
end

yline( ...
    phi_command_deg, ...
    'k--', ...
    '\phi_c = 30^\circ', ...
    'LineWidth',1.4, ...
    'HandleVisibility','off');

grid on
box on

xlabel('Time [s]')
ylabel('\phi [deg]')

title('LQ Servo Response for Different Initial Conditions')

legend( ...
    'Location','southeast', ...
    'Interpreter','none')

xlim([0 5])
ylim([-6 32])