%% ============================================================
% Question 4
% Final comparison of all selected controllers
%% ============================================================

clear
close all
clc

%% Controller names

controllerNames = { ...
    'P', ...
    'p + \phi', ...
    'Phase Lead', ...
    'Full State', ...
    'Observer \phi', ...
    'Observer p', ...
    'LQ Servo'};

numberOfControllers = numel(controllerNames);

%% ============================================================
% Final values from the report
%% ============================================================

% Settling time [s]
settlingTime = [ ...
    4.2624, ...
    3.3348, ...
    1.7862, ...
    2.2228, ...
    2.2228, ...
    2.2228, ...
    1.4629];

% Steady-state error [%]
steadyStateError = [ ...
    9.7835, ...
    6.5594, ...
    6.1473, ...
    0, ...
    0, ...
    0, ...
    0];

% Maximum actual aileron deflection [deg]
maxAileronDeflection = [ ...
    1.2173, ...
    1.6773, ...
    2.9479, ...
    0.9898, ...
    0.9898, ...
    0.9898, ...
    2.0220];

aileronLimit = 5;

%% ============================================================
% Create comparison figure
%% ============================================================

figure( ...
    'Color','w', ...
    'Name','Controller Performance Comparison', ...
    'Position',[70 120 1400 590]);

comparisonLayout = tiledlayout( ...
    1,3, ...
    'TileSpacing','compact', ...
    'Padding','compact');

title( ...
    comparisonLayout, ...
    'Question 4 - Selected Controller Performance Comparison', ...
    'FontSize',16, ...
    'FontWeight','bold');

%% Settling time

ax1 = nexttile;

bar(ax1,settlingTime,0.65);

grid(ax1,'on')
box(ax1,'on')

title(ax1,'Settling Time')
ylabel(ax1,'Time [s]')

xticks(ax1,1:numberOfControllers)
xticklabels(ax1,controllerNames)
xtickangle(ax1,35)

ax1.TickLabelInterpreter = 'tex';
ax1.FontSize = 10;

ylim(ax1,[0 5])

for k = 1:numberOfControllers

    text( ...
        ax1, ...
        k, ...
        settlingTime(k)+0.08, ...
        sprintf('%.3f',settlingTime(k)), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', ...
        'FontSize',9);
end

%% Steady-state error

ax2 = nexttile;

bar(ax2,steadyStateError,0.65);

grid(ax2,'on')
box(ax2,'on')

title(ax2,'Steady-State Error')
ylabel(ax2,'Error [%]')

xticks(ax2,1:numberOfControllers)
xticklabels(ax2,controllerNames)
xtickangle(ax2,35)

ax2.TickLabelInterpreter = 'tex';
ax2.FontSize = 10;

ylim(ax2,[0 11])

for k = 1:numberOfControllers

    if steadyStateError(k) == 0
        labelHeight = 0.2;
    else
        labelHeight = steadyStateError(k)+0.18;
    end

    text( ...
        ax2, ...
        k, ...
        labelHeight, ...
        sprintf('%.2f%%',steadyStateError(k)), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', ...
        'FontSize',9);
end

%% Maximum aileron deflection

ax3 = nexttile;

bar(ax3,maxAileronDeflection,0.65);

hold(ax3,'on')

yline( ...
    ax3, ...
    aileronLimit, ...
    'r--', ...
    '5 deg limit', ...
    'LineWidth',1.5, ...
    'LabelHorizontalAlignment','right');

grid(ax3,'on')
box(ax3,'on')

title(ax3,'Peak Aileron Deflection')
ylabel(ax3,'max |\delta_a| [deg]')

xticks(ax3,1:numberOfControllers)
xticklabels(ax3,controllerNames)
xtickangle(ax3,35)

ax3.TickLabelInterpreter = 'tex';
ax3.FontSize = 10;

ylim(ax3,[0 5.4])

for k = 1:numberOfControllers

    text( ...
        ax3, ...
        k, ...
        maxAileronDeflection(k)+0.08, ...
        sprintf('%.3f',maxAileronDeflection(k)), ...
        'HorizontalAlignment','center', ...
        'VerticalAlignment','bottom', ...
        'FontSize',9);
end

%% Export high-resolution image for Word

exportgraphics( ...
    gcf, ...
    'Question4_Controller_Comparison.png', ...
    'Resolution',300);